config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :memo, length: {maximum:200}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_url, notice: "スケジュールを登録しました"
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_url, notice: "スケジュールを更新しました"
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to events_url, notice: "スケジュール「#{event.title}」を削除しました。"
  end

  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :all_day, :memo)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.slim
.main_container   
    h2 スケジュール更新
    = render "shared/error", obj: @event

    .nav.justify-content-end 
        = link_to 'スケジュール一覧に戻る', events_path, class: 'nav-link'
    
    = render partial: 'shared/form', locals: { event: @event }

app/views/events/index.html.slim
.main_container
    .infomation 
        h2 スケジュール一覧


    div.container 
        table.table
            thead 
                tr 
                    th ID 
                    th タイトル
                    th 開始日
                    th 終了日
                    th 終日
                    th スケジュール更新日時
                    th 確認
                    th 編集
                    th 削除
            tbody 
                - @events.each do |event|
                    tr 
                        td = event.id 
                        td = event.title
                        td = event.start_date.to_s(:datetime_jp)
                        td = event.end_date.to_s(:datetime_jp)
                        td 
                            - if event.all_day == "1"
                                p ◯
                        td = event.updated_at.to_s(:datetime_jp)
                        td = link_to "確認", event, class: 'btn btn-primary'
                        td = link_to "編集", edit_event_path(event), class: 'btn btn-primary'
                        td = button_to "削除", event, method: :delete, class: 'btn btn-danger'
    = link_to '新規登録', new_event_path, class: 'btn btn-primary ms-3'

app/views/events/new.html.slim
.main_container   
    h2 スケジュール新規登録
   
    = render "shared/error", obj: @event

    .nav.justify-content-end 
        = link_to 'スケジュール一覧に戻る', events_path, class: 'nav-link'

    = render partial: 'shared/form', locals: { event: @event }

app/views/events/show.html.slim
.main_container
    h2 スケジュール詳細

    .nav.justify-content-end 
        = link_to 'スケジュール一覧に戻る', events_path, class: 'nav-link'

    table.table
        tbody
            tr 
                th = Event.human_attribute_name(:id)
                td = @event.id
            tr 
                th = Event.human_attribute_name(:title)
                td = @event.title
            tr 
                th = Event.human_attribute_name(:start_date)
                td = @event.start_date.to_s(:datetime_jp)
            tr 
                th = Event.human_attribute_name(:end_date)
                td = @event.end_date.to_s(:datetime_jp)
            tr 
                th = Event.human_attribute_name(:all_day)
                td 
                    - if @event.all_day == "1"
                        p ◯
            tr 
                th = Event.human_attribute_name(:created_at)
                td = @event.created_at.to_s(:datetime_jp)
            tr 
                th = Event.human_attribute_name(:updated_at)
                td = @event.updated_at.to_s(:datetime_jp)
            tr 
                th = Event.human_attribute_name(:memo)
                td = simple_format(h(@event.memo), {}, sanitize: false, wrapper_tag: "div")
    = link_to "編集", edit_event_path, class: 'btn btn-primary mb-3'
    = button_to "削除", @event, method: :delete, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Myapp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload'
    = javascript_importmap_tags 
  body
    header
      div
        h1 Ruby on Rails スケジュール管理アプリ
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
    
    = yield

    footer 
      div 
        h1 = "現在の日時:#{Date.current.strftime("%Y年 %m月 %d日")} 　　　スケジュール合計:#{Event.all.count}"

app/views/shared/_error.html.slim
- if obj.errors.any? 
    - obj.errors.full_messages.each do |message|
        ul
            li  = message

      

app/views/shared/_form.html.slim
= form_with model: event, local: true do |f|
    table.table
        tr.form-group 
            th = f.label :title
            td = f.text_field :title, class: 'form-control', id: 'event_title'
        tr.form-group 
            th = f.label :start_date
            td = f.datetime_field :start_date
        tr.form-group 
            th = f.label :end_date
            td = f.datetime_field :end_date
        tr.form-group 
            th = f.label :all_day
            td 
                = f.check_box :all_day, class: 'me-3'
                = f.label :all_day, "終日の場合はチェックを入れてください"
        tr.from-group 
            th = f.label :memo
            td = f.text_area :memo, class: 'form-control', id: 'event_memo'
    = f.submit nil, class: 'btn btn-primary'